name: ShenZhenZJJMonitor

on:
  workflow_dispatch:
  schedule:
    - cron: '0 16,17,18,19,20,21,22,23,0,1,2,3,4,5,6,7 * * *'


jobs:
  monitor-job:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4
      - name: 安装Python依赖
        run: pip install requests beautifulsoup4
      - name: 运行监控脚本
        run: python monitor.py
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PWD: ${{ secrets.SENDER_PWD }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
